#!/bin/sh

#install chef-solo on ubuntu

echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list

#Add the GPG Key and update index
sudo mkdir -p /etc/apt/trusted.gpg.d
gpg --keyserver keys.gnupg.net --recv-keys 83EF826A
gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null

#Update apt-get
sudo apt-get update

#Install opscode-keyring package
sudo apt-get install opscode-keyring #permanent upgradeable keyring

#Upgrade existing packages
sudo apt-get upgrade

#Install chef
echo "chef chef/chef_server_url string none" | sudo debconf-set-selections && sudo apt-get install chef -y
